baseURL = 'https://nicola.strappazzon.me/'
languageCode = 'es-es'
title = 'Nicola Strappazzon'

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Electrónica"
    url = "/electronic/"
    weight = 2

  [[menu.main]]
    name = "Cultura"
    url = "/cultura/"
    weight = 3

  [[menu.main]]
    name = "Diccionario"
    url = "/diccionary/"
    weight = 4

#   [[menu.main]]
#     name = "Acerca de mí"
#     url = "/about/"
#     weight = 5

[markup.goldmark.parser.attribute]
	block = true
[markup.goldmark.renderer]
  unsafe = true
